//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Dandabu.AttendanceTracker.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attendance_Data
    {
        public int Id { get; set; }
        public Nullable<int> Boys { get; set; }
        public Nullable<int> Girls { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Message_Id { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
    }
}
